/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupassignment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ywkok
 */
public class admin_product extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN_product
     */
    public admin_product() {
        initComponents();
        SelectProduct();
        Popup_add.setVisible(false);
        Popup_delete.setVisible(false);
    }
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    
    public void SelectProduct()
    {
        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/TestDB","YRCheng","8033");
            St = Con.createStatement();
            Rs = St.executeQuery("Select * from YRCheng.PRODUCTTB");
            ProTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popup_add = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        ProID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ProName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ProQuantity = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ProSale = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ProPurchase = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ProCategory = new javax.swing.JComboBox<>();
        Popup_add_cancelbtn = new javax.swing.JButton();
        Popup_add_addbtn = new javax.swing.JButton();
        Popup_delete = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Popup_delete_cancelbtn = new javax.swing.JButton();
        Popup_delete_deletebtn = new javax.swing.JButton();
        Delete_ID = new javax.swing.JLabel();
        Delete_purchase = new javax.swing.JLabel();
        Delete_category = new javax.swing.JLabel();
        Delete_price = new javax.swing.JLabel();
        Delete_quantity = new javax.swing.JLabel();
        Delete_name = new javax.swing.JLabel();
        Popup_update = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Popup_update_cancelbtn = new javax.swing.JButton();
        Popup_update_updatebtn = new javax.swing.JButton();
        Update_ID = new javax.swing.JLabel();
        Update_purchase = new javax.swing.JLabel();
        Update_category = new javax.swing.JLabel();
        Update_quantity = new javax.swing.JLabel();
        Update_name = new javax.swing.JLabel();
        Update_price = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Salespage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Sellerpage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProTable = new javax.swing.JTable();
        ProDeletebtn = new javax.swing.JButton();
        ProUpdatebtn = new javax.swing.JButton();
        ProAddbtn = new javax.swing.JButton();

        Popup_add.setMinimumSize(new java.awt.Dimension(610, 350));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 320));

        ProID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProIDActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Set Name");

        ProName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProNameActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Product ID");

        ProQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProQuantityActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Quantity");

        ProSale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProSaleActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Category");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Purchase Price");

        ProPurchase.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProPurchaseActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Sale Price");

        ProCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ProCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NBA", "NFL", "Item 3", "Item 4" }));

        Popup_add_cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_add_cancelbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_add_cancelbtn.setText("CANCEL");
        Popup_add_cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_add_cancelbtnActionPerformed(evt);
            }
        });

        Popup_add_addbtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_add_addbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_add_addbtn.setText("ADD");
        Popup_add_addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_add_addbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProID, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(ProName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(ProQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(ProSale, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(ProPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(ProCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Popup_add_cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(455, Short.MAX_VALUE)
                    .addComponent(Popup_add_addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProID)
                    .addComponent(ProCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(Popup_add_cancelbtn)
                .addGap(21, 21, 21))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(248, Short.MAX_VALUE)
                    .addComponent(Popup_add_addbtn)
                    .addGap(21, 21, 21)))
        );

        javax.swing.GroupLayout Popup_addLayout = new javax.swing.GroupLayout(Popup_add.getContentPane());
        Popup_add.getContentPane().setLayout(Popup_addLayout);
        Popup_addLayout.setHorizontalGroup(
            Popup_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Popup_addLayout.setVerticalGroup(
            Popup_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Popup_delete.setMinimumSize(new java.awt.Dimension(610, 350));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Product ID       ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Category          ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Set Name         ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Quantity            ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Sale Price          ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Purchase Price  ");

        Popup_delete_cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_delete_cancelbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_delete_cancelbtn.setText("CANCEL");
        Popup_delete_cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_delete_cancelbtnActionPerformed(evt);
            }
        });

        Popup_delete_deletebtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_delete_deletebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_delete_deletebtn.setText("DELETE");
        Popup_delete_deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_delete_deletebtnActionPerformed(evt);
            }
        });

        Delete_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_ID.setText(":  ");

        Delete_purchase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_purchase.setText(":  ");

        Delete_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_category.setText(":  ");

        Delete_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_price.setText(":  ");

        Delete_quantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_quantity.setText(":  ");

        Delete_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delete_name.setText(":  ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_category, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_price, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete_name, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(Popup_delete_cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Popup_delete_deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Delete_ID)
                        .addGap(93, 93, 93)
                        .addComponent(Delete_purchase)
                        .addGap(13, 13, 13)
                        .addComponent(Delete_price))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Delete_name))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Delete_category))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Delete_quantity))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel14)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel13)))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Popup_delete_cancelbtn)
                    .addComponent(Popup_delete_deletebtn)))
        );

        javax.swing.GroupLayout Popup_deleteLayout = new javax.swing.GroupLayout(Popup_delete.getContentPane());
        Popup_delete.getContentPane().setLayout(Popup_deleteLayout);
        Popup_deleteLayout.setHorizontalGroup(
            Popup_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Popup_deleteLayout.setVerticalGroup(
            Popup_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Popup_update.setMinimumSize(new java.awt.Dimension(610, 350));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Product ID       ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Category          ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Set Name         ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Quantity            ");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Sale Price          ");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Purchase Price  ");

        Popup_update_cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_update_cancelbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_update_cancelbtn.setText("CANCEL");
        Popup_update_cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_update_cancelbtnActionPerformed(evt);
            }
        });

        Popup_update_updatebtn.setBackground(new java.awt.Color(255, 255, 255));
        Popup_update_updatebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Popup_update_updatebtn.setText("UPDATE");
        Popup_update_updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Popup_update_updatebtnActionPerformed(evt);
            }
        });

        Update_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_ID.setText(":  ");

        Update_purchase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_purchase.setText(":  ");

        Update_category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_category.setText(":  ");

        Update_quantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_quantity.setText(":  ");

        Update_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_name.setText(":  ");

        Update_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Update_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_priceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Update_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(Update_category, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(Update_quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(Update_purchase, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(Update_name, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(Update_price)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(Popup_update_cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Popup_update_updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Update_ID)
                        .addGap(93, 93, 93)
                        .addComponent(Update_purchase))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel22)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(Update_name))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(Update_category))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(Update_quantity))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel27)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(Update_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Popup_update_cancelbtn)
                    .addComponent(Popup_update_updatebtn)))
        );

        javax.swing.GroupLayout Popup_updateLayout = new javax.swing.GroupLayout(Popup_update.getContentPane());
        Popup_update.getContentPane().setLayout(Popup_updateLayout);
        Popup_updateLayout.setHorizontalGroup(
            Popup_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Popup_updateLayout.setVerticalGroup(
            Popup_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(50, 151, 95));
        jLabel3.setText("Card Collection ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(50, 151, 95));
        jLabel4.setText("Hobby Store");

        Salespage.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Salespage.setForeground(new java.awt.Color(255, 255, 255));
        Salespage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salespage.setText("Sales");
        Salespage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalespageMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(50, 151, 90));
        jLabel5.setText("Product");

        Sellerpage.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Sellerpage.setForeground(new java.awt.Color(255, 255, 255));
        Sellerpage.setText("Seller");
        Sellerpage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellerpageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Salespage)
                                .addComponent(Sellerpage)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(88, 88, 88)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(Sellerpage)
                .addGap(39, 39, 39)
                .addComponent(Salespage)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel7.setText("Product Management");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NBA", "NFL", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Categories Filter");

        jScrollPane1.setBackground(new java.awt.Color(50, 151, 90));
        jScrollPane1.setForeground(new java.awt.Color(50, 151, 90));

        ProTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Category", "Set Name", "Purchase", "Sale", "Quantity"
            }
        ));
        ProTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ProTable.setRowHeight(25);
        ProTable.setSelectionBackground(new java.awt.Color(55, 151, 90));
        ProTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ProTable);

        ProDeletebtn.setBackground(new java.awt.Color(255, 255, 255));
        ProDeletebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProDeletebtn.setText("DELETE");
        ProDeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProDeletebtnActionPerformed(evt);
            }
        });

        ProUpdatebtn.setBackground(new java.awt.Color(255, 255, 255));
        ProUpdatebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProUpdatebtn.setText("UPDATE");
        ProUpdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProUpdatebtnActionPerformed(evt);
            }
        });

        ProAddbtn.setBackground(new java.awt.Color(255, 255, 255));
        ProAddbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProAddbtn.setText("ADD");
        ProAddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProAddbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProAddbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(ProUpdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(ProDeletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jLabel7)))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProUpdatebtn)
                            .addComponent(ProDeletebtn)
                            .addComponent(ProAddbtn))
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ProDeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProDeletebtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)ProTable.getModel();
        int Myindex = ProTable.getSelectedRow();
        if(Myindex == -1)
        {
            JOptionPane.showMessageDialog(this,"Select the Product to be delete");
        }else
        {
            Delete_ID.setText(model.getValueAt(Myindex,0).toString());
            Delete_name.setText(model.getValueAt(Myindex, 2).toString());
            Delete_category.setText(model.getValueAt(Myindex, 1).toString());
            Delete_quantity.setText(model.getValueAt(Myindex,5).toString());
            Delete_purchase.setText(model.getValueAt(Myindex,3).toString());
            Delete_price.setText(model.getValueAt(Myindex,4).toString());
            Popup_delete.setVisible(true);
        }
        
    }//GEN-LAST:event_ProDeletebtnActionPerformed

    private void ProUpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProUpdatebtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)ProTable.getModel();
        int Myindex = ProTable.getSelectedRow();
        if(Myindex == -1)
        {
            JOptionPane.showMessageDialog(this,"Select the Product to be update");
        }else
        {
            Update_ID.setText(model.getValueAt(Myindex,0).toString());
            Update_name.setText(model.getValueAt(Myindex, 2).toString());
            Update_category.setText(model.getValueAt(Myindex, 1).toString());
            Update_quantity.setText(model.getValueAt(Myindex,5).toString());
            Update_purchase.setText(model.getValueAt(Myindex,3).toString());
            Update_price.setText(model.getValueAt(Myindex,4).toString());
            Popup_update.setVisible(true);
        }
        
    }//GEN-LAST:event_ProUpdatebtnActionPerformed

    private void ProAddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProAddbtnActionPerformed
        // TODO add your handling code here:
        Popup_add.setVisible(true);
    }//GEN-LAST:event_ProAddbtnActionPerformed

    private void ProIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProIDActionPerformed

    private void ProNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProNameActionPerformed

    private void ProQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProQuantityActionPerformed

    private void ProSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProSaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProSaleActionPerformed

    private void ProPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProPurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProPurchaseActionPerformed

    private void Popup_add_cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_add_cancelbtnActionPerformed
        // TODO add your handling code here:
        Popup_add.setVisible(false);
        ProID.setText("");
        ProName.setText("");
        ProPurchase.setText("");
        ProSale.setText("");
        ProQuantity.setText("");
    }//GEN-LAST:event_Popup_add_cancelbtnActionPerformed

    private void Popup_add_addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_add_addbtnActionPerformed
        // TODO add your handling code here:
        if(ProID.getText().isEmpty() || ProName.getText().isEmpty()||ProPurchase.getText().isEmpty()||ProQuantity.getText().isEmpty()||ProSale.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Missing Information");
        }
        else
        {
            try{
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/TestDB","YRCheng","8033");
                PreparedStatement add = Con.prepareStatement("insert into PRODUCTTB values(?,?,?,?,?,?)");
                add.setInt(1, Integer.valueOf(ProID.getText()));
                add.setString(2, ProCategory.getSelectedItem().toString());
                add.setString(3, ProName.getText());
                add.setInt(4, Integer.valueOf(ProPurchase.getText()));
                add.setInt(5, Integer.valueOf(ProSale.getText()));
                add.setInt(6, Integer.valueOf(ProQuantity.getText()));
                int row = add.executeUpdate();
                Popup_add.setVisible(false);
                JOptionPane.showMessageDialog(this,"Product Added Successfully");
                Con.close();
                ProID.setText("");
                ProName.setText("");
                ProPurchase.setText("");
                ProSale.setText("");
                ProQuantity.setText("");
                SelectProduct();
            }catch (Exception e)
            {
                System.out.println("HERE?????");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Popup_add_addbtnActionPerformed

    private void Popup_delete_cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_delete_cancelbtnActionPerformed
        // TODO add your handling code here:
        Popup_delete.setVisible(false);
    }//GEN-LAST:event_Popup_delete_cancelbtnActionPerformed

    private void Popup_delete_deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_delete_deletebtnActionPerformed
        // TODO add your handling code here:
        try{
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/TestDB","YRCheng","8033");
                String ProductID = Delete_ID.getText();
                String Query = "Delete from YRCheng.PRODUCTTB where PROID="+ProductID;
                Statement Add = Con.createStatement();
                Add.executeUpdate(Query);
                SelectProduct();
                JOptionPane.showMessageDialog(this,"Product Deleted Successfully");
                Popup_delete.setVisible(false);
            }catch(Exception e)
            {
                e.printStackTrace();
            }
    }//GEN-LAST:event_Popup_delete_deletebtnActionPerformed

    private void Popup_update_cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_update_cancelbtnActionPerformed
        // TODO add your handling code here:
        Popup_update.setVisible(false);
    }//GEN-LAST:event_Popup_update_cancelbtnActionPerformed

    private void Popup_update_updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Popup_update_updatebtnActionPerformed
        // TODO add your handling code here:
        if(Update_price.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Missing Information");
        }
        else
        {
            try{
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/TestDBb","YRCheng","8033");
                String Query = "Update YRCheng.PRODUCTTB set PROSALE="+Update_price.getText()+"where PROID="+Update_ID.getText();
                Statement Add = Con.createStatement();
                Add.executeUpdate(Query);
                SelectProduct();
                JOptionPane.showMessageDialog(this,"Product Updated");
                Popup_update.setVisible(false);
            }catch (Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Popup_update_updatebtnActionPerformed

    private void Update_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_priceActionPerformed

    private void SellerpageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellerpageMouseClicked
        // TODO add your handling code here:
        reg.adminform2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellerpageMouseClicked

    private void SalespageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalespageMouseClicked
        // TODO add your handling code here:
        reg.adminform3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalespageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Delete_ID;
    private javax.swing.JLabel Delete_category;
    private javax.swing.JLabel Delete_name;
    private javax.swing.JLabel Delete_price;
    private javax.swing.JLabel Delete_purchase;
    private javax.swing.JLabel Delete_quantity;
    private javax.swing.JDialog Popup_add;
    private javax.swing.JButton Popup_add_addbtn;
    private javax.swing.JButton Popup_add_cancelbtn;
    private javax.swing.JDialog Popup_delete;
    private javax.swing.JButton Popup_delete_cancelbtn;
    private javax.swing.JButton Popup_delete_deletebtn;
    private javax.swing.JDialog Popup_update;
    private javax.swing.JButton Popup_update_cancelbtn;
    private javax.swing.JButton Popup_update_updatebtn;
    private javax.swing.JButton ProAddbtn;
    private javax.swing.JComboBox<String> ProCategory;
    private javax.swing.JButton ProDeletebtn;
    private javax.swing.JTextField ProID;
    private javax.swing.JTextField ProName;
    private javax.swing.JTextField ProPurchase;
    private javax.swing.JTextField ProQuantity;
    private javax.swing.JTextField ProSale;
    private javax.swing.JTable ProTable;
    private javax.swing.JButton ProUpdatebtn;
    private javax.swing.JLabel Salespage;
    private javax.swing.JLabel Sellerpage;
    private javax.swing.JLabel Update_ID;
    private javax.swing.JLabel Update_category;
    private javax.swing.JLabel Update_name;
    private javax.swing.JTextField Update_price;
    private javax.swing.JLabel Update_purchase;
    private javax.swing.JLabel Update_quantity;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
